version: '3.7'

services:
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    command: ["start-dev"]
    ports:
      - "8080:8080"
    environment:
      KEYCLOAK_DB_URL: jdbc:h2:tcp://localhost/opt/keycloak/data/h2/keycloakdb
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KEYCLOAK_IMPORT: /opt/keycloak/data/import/realm-config.json 
    networks:
      - keycloak-network
    volumes:
      - keycloak-data:/opt/keycloak/data
      - ./realm-config.json:/opt/keycloak/data/import/realm-config.json  
    restart: always

volumes:
  keycloak-data:

networks:
  keycloak-network:
    driver: bridge